spring:
  profiles:
    active: dev # By default, the active profile is "dev". During production, it will be replaced to "prod" due to Azure's environment variables.
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80
