scrape_configs:
  - job_name: "hogwarts-artifacts-online"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s # how often to scrape
    static_configs:
      - targets: ["docker.for.mac.localhost:80"] # This is for demo purpose. During  production, change this to the production host address.
